site_name: riweather
site_author: John Ensley
repo_url: https://github.com/ensley-nexant/riweather/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: ri
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - toc.follow
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Installation: install.md
  - Getting Started: getting_started.ipynb
  - Data Resampling Introduction: data_resampling.ipynb
  - Command Line Interface: cli.md
  - API Reference: reference.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - smarty
  - toc:
      permalink: True
  - mkdocs-click
  - attr_list
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://python-visualization.github.io/folium/latest/objects.inv
          options:
            docstring_options:
              ignore_init_summary: True
              trim_doctest_flags: True
            docstring_section_style: "list"
            docstring_style: google
            heading_level: 3
            line_length: 100
            merge_init_into_class: True
            parameter_headings: True
            separate_signature: True
            show_root_heading: True
            show_root_toc_entry: false
            show_symbol_type_heading: True
            show_symbol_type_toc: True
            signature_crossrefs: True
  - mknotebooks:
      execute: false
      timeout: 100
      allow_errors: false
copyright: "Copyright &copy; 2022-2025 RESOURCE INNOVATIONS. All rights reserved."
