site_name: riweather
site_author: John Ensley
site_url: https://ensley-nexant.github.io/riweather/
repo_url: https://github.com/ensley-nexant/riweather/
theme:
  name: material
  font:
    text: Red Hat Text
    code: Red Hat Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: ri
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
extra_css:
  - stylesheets/extra.css
nav:
  - Get Started:
    - Welcome: index.md
    - Installation: install.md
  - Examples:
    - Quick How-To: how_to.ipynb
    - Data Resampling Introduction: resampling.ipynb
  - About the Data:
    - The Integrated Surface Dataset: about/integrated_surface_dataset.md
    - Structure of riweather Data: about/structure.md
    - Shorthand Codes: about/shorthand_codes.md
  - Command Line Interface: cli.md
  - API Reference:
    - Station: api/station.md
    - Parser: api/parser.md
    - Rollup functions: api/rollup.md
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - mkdocs-click
  - pymdownx.extra
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - smarty
  - toc:
      permalink: true
      title: On this page
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://matplotlib.org/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://python-visualization.github.io/folium/latest/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            docstring_section_style: list
            docstring_style: google
            extensions:
            - griffe_pydantic:
                schema: true
            line_length: 100
            members_order: source
            merge_init_into_class: true
            parameter_headings: false
            separate_signature: true
            show_root_full_path: true
            show_root_heading: true
            show_root_members_full_path: false
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            unwrap_annotated: true
  - mknotebooks:
      execute: false
      timeout: 100
      allow_errors: false
copyright: "Copyright &copy; 2022-2025 RESOURCE INNOVATIONS. All rights reserved."
