[tool.poetry]
name = "riweather"
version = "0.1.0"
description = "Grab publicly available weather data"
authors = ["John Ensley <jensley@resource-innovations.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/ensley-nexant/riweather"
repository = "https://github.com/ensley-nexant/riweather"
keywords = ["weather", "noaa"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
requests = "^2.28.1"
sqlalchemy = "^1.4.45"
pyshp = "^2.3.1"
shapely = "^2.0.0"
pandas = "^1.5.2"

[tool.poetry.scripts]
riweather = "riweather.cli:main"


[tool.poetry.group.tests.dependencies]
pytest = "^7.2.0"
coverage = {extras = ["toml"], version = "^7.0.1"}
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["riweather"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
